Logical: TBProgram
Title: "TB program"
Parent: Base
* enrollmentDate 1..1 date "Start of treatment date"
* incidentDate 0..1 date "Start of treatment date"
* firstName 1..1 string "This is the person's first name"
* lastName 1..1 string "Last name"
* gender 1..1 code "Gender"
* gender from GenderVS (required)
* tbIdentifier 0..1 string "TB identifier"
* age 0..1 Age "Age"
* address 0..1 string "Country"
* city 0..1 string "City"
* state 0..1 string "State"
* zipCode 0..1 decimal "Zip code"
* email 0..1 string "Email address"
* phoneNumber 0..1 string "Phone number"
* residenceLocation 0..1 string "Residence location"
* motherMaidenName 0..1 string "Mother maiden name"
* nationalIdentifier 0..1 string "National identifier"
* occupation 0..1 string "Occupation"
* company 0..1 string "Company"
* tbNumber 0..1 string "TB number"
* vehicle 0..1 string "Vehicle"
* bloodType 0..1 string "Blood type"
* weightInKg 0..1 decimal "Weight in kg"
* heightInCm 0..1 decimal "Height in cm"
* latitude 0..1 string "Latitude"
* longitude 0..1 string "Longitude"
* uniqueIdentifier 0..1 string "Unique identiifer"
* labMonitoring 0..* LabMonitoring "Laboratory monitoring"
* tbVisit 0..1 TBVisit "Routine TB visit"
* sputumSmearMicroscopyTest 0..* SputumSmearMicroscopyTest "Sputum smear microscopy test"